module.exports = [
  { type: 'colors', name: 'Brown', colorValue: '#6E473B' },
  { type: 'colors', name: 'Black', colorValue: '#000000' },
  { type: 'colors', name: 'Blue', colorValue: '#2B3E7A' },
  { type: 'colors', name: 'Cream', colorValue: '#D2C4B1' },
  { type: 'colors', name: 'Gold', colorValue: '#B1A066' },
  { type: 'colors', name: 'Green', colorValue: '#5A9E48' },
  { type: 'colors', name: 'Ivory', colorValue: '#FDFBF7' },
  { type: 'colors', name: 'Orange', colorValue: '#EB6824' },
  { type: 'colors', name: 'Pearl', colorValue: '#E5E4DE' },
  { type: 'colors', name: 'Pink', colorValue: '#C51B60' },
  { type: 'colors', name: 'Red', colorValue: '#D8232A' },
  { type: 'colors', name: 'Teal', colorValue: '#0A7D84' },
  { type: 'colors', name: 'White', colorValue: '#FFFFFF' },
  { type: 'colors', name: 'Gray', colorValue: '#555555' },
  { type: 'colors', name: 'Yellow', colorValue: '#F4B324' },
  { type: 'colors', name: 'Multicolor', colorValue: 'linear-gradient(45deg, #FF0055, #00FF55, #0055FF, #FFFF00)' },
  { type: 'size', width: 12, height: 12, displayValue: '12X12' },
  { type: 'size', width: 12, height: 22, displayValue: '12x22' },
  { type: 'size', width: 12, height: 8, displayValue: '12x8' },
  { type: 'size', width: 15, height: 10, displayValue: '15x10' },
  { type: 'size', width: 16, height: 16, displayValue: '16x16' },
  { type: 'size', width: 18, height: 12, displayValue: '18x12' },
  { type: 'size', width: 20, height: 20, displayValue: '20x20' },
  { type: 'size', width: 24, height: 12, displayValue: '24x12' },
  { type: 'size', width: 24, height: 24, displayValue: '24x24' },
  { type: 'size', width: 40, height: 8, displayValue: '40x8' },
  { type: 'size', width: 48, height: 24, displayValue: '48x24' },
  { type: 'size', width: 64, height: 32, displayValue: '64x32' },
  { type: 'size', width: 72, height: 48, displayValue: '72x48' },
  { type: 'size', width: 96, height: 32, displayValue: '96x32' },
  { type: 'thickness', thickness: 6, displayValue: '6 mm' },
  { type: 'thickness', thickness: 7, displayValue: '7 mm' },
  { type: 'thickness', thickness: 8.5, displayValue: '8.5 mm' },
  { type: 'thickness', thickness: 9, displayValue: '9 mm' },
  { type: 'thickness', thickness: 10, displayValue: '10 mm' },
  { type: 'thickness', thickness: 12, displayValue: '12 mm' },
  { type: 'thickness', thickness: 15, displayValue: '15 mm' },
  { type: 'thickness', thickness: 20, displayValue: '20 mm' },
];
